repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.6
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.4.0
  hooks:
    - id: python-use-type-annotations
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.4.0
  hooks:
    - id: reorder-python-imports
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
    - id: flake8
